### ISSUE TITLE
ex 1.7: Good job but there is an inefficiency 

### ISSUE THREAD

**Issue by betakuwe** [StrwBrriShrtcke/Practice#2]
https://github.com/StrwBrriShrtcke/Practice/blob/b4cafe270be4a9d3e7521f22b969df24ed305e20/Ex1.7#L9-L11

https://github.com/StrwBrriShrtcke/Practice/blob/b4cafe270be4a9d3e7521f22b969df24ed305e20/Ex1.7#L21-L25

As discussed:

> At each iteration of `sqrt_iter`, it calls `is_good_enough` which then calls `improve`, if it's not good enough, `sqrt_iter` will call `improve` again. So at each iteration, `improve` is called twice with the same exact arguments. Try to optimize this such that `improve` is only called once at each iteration.

**Comment by StrwBrriShrtcke** [comment]
sqrt_iter has been optimized thank u :))
